// Texty dokladov (faktúra, ponuka, upomienka) v slovenčine a nemčine
const T = {
  sk: {
    invoice: 'FAKTÚRA', quote: 'CENOVÁ PONUKA', vs: 'Variabilný symbol', supplier: 'Dodávateľ', customer: 'Odberateľ', ico: 'IČO', dic: 'DIČ', vatid: 'IČ DPH', register: 'Zápis', dates: 'Dátumy', issue: 'Dátum vystavenia', delivery: 'Dátum dodania', due: 'Dátum splatnosti', period: 'Fakturačné obdobie', site: 'Stavba / zákazka', payment: 'Platba', iban: 'IBAN', bic: 'BIC/SWIFT', method: 'Forma úhrady', transfer: 'bankový prevod', reference: 'Variabilný symbol', desc: 'Popis', qty: 'Množstvo', unit: 'MJ', price: 'Cena / MJ', total: 'Spolu', net: 'Základ dane', vat: 'DPH', gross: 'Spolu s DPH', retention: 'Zádržné', retention_due: 'splatné', withholding: 'Zrážková daň zo stavebných prác (§ 48 EStG) 15 %', due_amount: 'K úhrade', skonto: (d, p, a) => `Pri úhrade do ${d} poskytujeme skonto ${p} %: suma k úhrade so skontom ${a}.`, retention_note: (a, d) => `Zádržné vo výške ${a} bude uvoľnené ${d}.`, rc_eu: 'Dodanie služby je oslobodené od DPH – prenesenie daňovej povinnosti na príjemcu služby podľa § 15 ods. 1 zákona č. 222/2004 Z. z. a čl. 196 smernice 2006/112/ES (Reverse charge).', rc_domestic: 'Prenesenie daňovej povinnosti – daň odvedie príjemca plnenia podľa § 69 ods. 12 zákona č. 222/2004 Z. z. o DPH.', exempt: 'Dodávateľ nie je platiteľom DPH.', issued_by: 'Vystavil', stamp: 'Pečiatka a podpis', valid_until: 'Platnosť ponuky do', hours: 'hod', quote_intro: 'Na základe Vašej požiadavky Vám predkladáme cenovú ponuku na poskytnutie pracovníkov:', quote_terms: 'Ceny sú uvedené bez DPH za odpracovanú hodinu. Fakturácia mesačne na základe potvrdených hodinových lístkov.', overtime: 'nadčas', saturday: 'sobota', sunday: 'nedeľa / sviatok', night: 'nočná práca', surcharge: 'príplatok', week: 'T', aug: 'Povolenie na prenájom zamestnancov č.',
    mail_subject: (n) => `Faktúra č. ${n}`, mail_body: (n, due, amt, c) => `Dobrý deň,\n\nv prílohe Vám zasielame faktúru č. ${n} so splatnosťou ${due} na sumu ${amt} EUR.\n\nĎakujeme za spoluprácu.\n\nS pozdravom\n${c}`,
  },
  de: {
    invoice: 'RECHNUNG', quote: 'ANGEBOT', vs: 'Rechnungsnummer', supplier: 'Leistungserbringer', customer: 'Leistungsempfänger', ico: 'Reg.-Nr.', dic: 'Steuernummer', vatid: 'USt-IdNr.', register: 'Registereintrag', dates: 'Daten', issue: 'Rechnungsdatum', delivery: 'Leistungsdatum', due: 'Fälligkeitsdatum', period: 'Leistungszeitraum', site: 'Baustelle / Projekt', payment: 'Zahlung', iban: 'IBAN', bic: 'BIC/SWIFT', method: 'Zahlungsart', transfer: 'Überweisung', reference: 'Verwendungszweck', desc: 'Bezeichnung', qty: 'Menge', unit: 'Einheit', price: 'Einzelpreis', total: 'Gesamt', net: 'Nettobetrag', vat: 'USt.', gross: 'Bruttobetrag', retention: 'Sicherheitseinbehalt', retention_due: 'fällig am', withholding: 'Bauabzugsteuer gem. § 48 EStG 15 %', due_amount: 'Zahlbetrag', skonto: (d, p, a) => `Bei Zahlung bis zum ${d} gewähren wir ${p} % Skonto: Zahlbetrag mit Skonto ${a}.`, retention_note: (a, d) => `Der Sicherheitseinbehalt in Höhe von ${a} wird am ${d} fällig.`, rc_eu: 'Steuerschuldnerschaft des Leistungsempfängers (Reverse-Charge-Verfahren) gemäß § 13b UStG / Art. 196 MwStSystRL. Die Rechnung enthält keine Umsatzsteuer.', rc_domestic: 'Steuerschuldnerschaft des Leistungsempfängers.', exempt: 'Der Leistungserbringer ist nicht umsatzsteuerpflichtig.', issued_by: 'Erstellt von', stamp: 'Stempel und Unterschrift', valid_until: 'Angebot gültig bis', hours: 'Std.', quote_intro: 'Gerne unterbreiten wir Ihnen folgendes Angebot für die Überlassung von Arbeitskräften:', quote_terms: 'Alle Preise verstehen sich netto pro geleistete Arbeitsstunde. Abrechnung monatlich auf Basis der bestätigten Stundenzettel.', overtime: 'Überstunden', saturday: 'Samstag', sunday: 'Sonntag / Feiertag', night: 'Nachtarbeit', surcharge: 'Zuschlag', week: 'KW', aug: 'Erlaubnis zur Arbeitnehmerüberlassung Nr.',
    mail_subject: (n) => `Rechnung Nr. ${n}`, mail_body: (n, due, amt, c) => `Sehr geehrte Damen und Herren,\n\nanbei erhalten Sie unsere Rechnung Nr. ${n}, fällig am ${due}, über ${amt} EUR.\n\nVielen Dank für die gute Zusammenarbeit.\n\nMit freundlichen Grüßen\n${c}`,
  },
};
function t(lang) { return T[lang] || T.sk; }
module.exports = { t, T };
